---
title: "nbaR"
output: github_document
knit: (function(input, ...) { rmarkdown::render(input, output_file = "README.md", envir = globalenv()) })
---

### Loading Libraries

```{r message = F, warning = F}
library(tidyverse)
library(janitor)
library(tvthemes)
library(hoopR)

theme_custom = theme_avatar() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5, size = 9, vjust = 2.5, face = "italic"),
        plot.caption = element_text(face = "italic"),
        panel.grid.major = element_line(linewidth = 0.5, colour = "#D6D0C4"),
        panel.grid.minor = element_line(linewidth = 0.5, colour = "#D6D0C4"))

theme_set(theme_custom)
```

### Data Import

```{r}
# doing this to suppress warning message for every usage
# write_csv(load_nba_pbp(), "full_pbp.csv")
full_pbp = read_csv("full_pbp.csv", col_types = cols()) |>
  filter(home_team_abbrev != "LEB") # excludes all star game
```

### Adding Team Color Codes

```{r}
team_color_codes = c("#C8102E", "#000000", "#007A33", "#1D1160", "#CE1141", "#860038",
                     "#00538C", "#0E2240", "#C8102E", "#1D428A", "#CE1141", "#FDBB30",
                     "#C8102E", "#552583", "#5D76A9", "#98002E", "#00471B", "#236192",
                     "#0C2340", "#F58426", "#007AC1", "#0077C0", "#006BB6", "#1D1160",
                     "#E03A3E", "#C4CED4", "#5A2D81", "#CE1141", "#002B5C", "#E31837")

team_color_df = data.frame(team = sort(unique(full_pbp$home_team_abbrev)),
                           hex = team_color_codes)
```


### Getting End Game Data

```{r}
end_games = full_pbp |>
  filter(text == "End of Game") |>
  select(game_id, date = game_date, away_team = away_team_abbrev,
         away_score, home_score, home_team = home_team_abbrev) |>
  mutate(win_team = ifelse(home_score > away_score, home_team, away_team),
         lose_team = ifelse(home_score > away_score, away_team, home_team))

end_games
```

### Getting Team Records

```{r}
team_records = end_games |>
  count(win_team) |>
  rename(team = win_team, wins = n) |>
  left_join(end_games |>
  count(lose_team) |>
  rename(team = lose_team, losses = n), by = "team") |>
  mutate(pct = round(wins / (wins + losses), 3),
         record = paste0(wins, "-", losses))

team_records |>
  arrange(desc(pct))
```

### First to 69

```{r}
get_first_to_69 = function(gid) {
  return(full_pbp |>
    filter(game_id == gid) |>
    mutate(sequence_number = as.integer(sequence_number)) |>
    arrange(sequence_number) |>
    filter(home_score >= 69 | away_score >= 69) |>
    head(1) |>
    transmute(first_to_69 = ifelse(home_score >= 69, home_team_abbrev, away_team_abbrev)) |>
    pull(first_to_69))
}

# first_to_69_df = end_games |>
#   mutate(ft69 = sapply(game_id, get_first_to_69))

first_to_69_df = read_csv("first_to_69.csv", col_types = cols())

last_choke = first_to_69_df |>
  filter(win_team != ft69) |>
  slice_max(date, n = 1)

paste0("Most recent First to 69 choke: ", last_choke$ft69, " choke v. ",
       last_choke$win_team, " on ", month(last_choke$date, label = T, abbr = F),
       " ", day(last_choke$date), ", ", year(last_choke$date))
```

### Getting Offensive and Defensive PPG Data (Regular Season)

```{r}
get_off_ppg = function(team) {
  home_scores = end_games |> filter(home_team == team) |> pull(home_score)
  away_scores = end_games |> filter(away_team == team) |> pull(away_score)
  return(round(mean(c(home_scores, away_scores)), 3))
}

get_def_ppg = function(team) {
  home_scores = end_games |> filter(home_team == team) |> pull(away_score)
  away_scores = end_games |> filter(away_team == team) |> pull(home_score)
  return(round(mean(c(home_scores, away_scores)), 3))
}

team_ppg = data.frame(team = team_records$team) |>
  mutate(off_ppg = sapply(team, get_off_ppg),
         def_ppg = sapply(team, get_def_ppg))

team_ppg |>
  ggplot(aes(off_ppg, def_ppg)) +
  geom_point(aes(col = team), size = 4, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = team), size = 4) +
  geom_vline(aes(xintercept = mean(off_ppg)), linetype = "dashed", alpha = 0.5) +
  geom_hline(aes(yintercept = mean(def_ppg)), linetype = "dashed", alpha = 0.5) +
  scale_color_manual(values = team_color_codes) +
  labs(x = "Offensive PPG", y = "Defensive PPG",
       title = "Scatterplot of Offensive and Defensive PPG", subtitle = "2022-2023 Season") +
  scale_x_continuous(breaks = seq(100, 130, by = 2)) +
  scale_y_continuous(breaks = seq(100, 130, by = 2))
```

### Reframing End Game Data

```{r}
reframed_end_games = end_games |>
  group_by(game_id, date, team = home_team) |>
  reframe(opponent = away_team,
            team_score = home_score,
            opp_score = away_score) |>
  mutate(home_away = "home") |>
  rbind(end_games |>
  group_by(game_id, date, team = away_team) |>
  reframe(opponent = home_team,
          team_score = away_score,
          opp_score = home_score) |>
  mutate(home_away = "away"))

reframed_end_games
```

### xxx - third qtr leads

```{r}
end_games |>
  select(game_id, win_team, lose_team) |>
  inner_join(full_pbp |>
  filter(text == "End of the 3rd Quarter") |>
  transmute(game_id, win_3q = case_when(home_score > away_score ~ home_team_abbrev,
                                        home_score < away_score ~ away_team_abbrev,
                                        home_score == away_score ~ "Tied")), by = "game_id")
```

### Scorigami

```{r}
end_games |>
  transmute(date, home_team, away_team,
            win_score = ifelse(home_score > away_score, home_score, away_score),
            lose_score = ifelse(home_score > away_score, away_score, home_score)) |>
  count(win_score, lose_score) |>
  filter(between(win_score, 100, 125) & between(lose_score, 100, 125)) |>
  ggplot(aes(win_score, lose_score)) +
  geom_point(size = 3, col = "#C88F3E") +
  geom_abline(alpha = 0.5) +
  scale_x_continuous(breaks = seq(100, 125, by = 1)) +
  scale_y_continuous(breaks = seq(100, 125, by = 1)) +
  labs(x = "Winning Score", y = "Losing Score",
       title = "2022-2023 NBA Scorigami",
       subtitle = "For visualization purposes, only includes scores between 100 and 125",
       caption = "Data: NBA.com via {hoopR}")
```

### historic final scores + last time a score happened

```{r message = F, warning = F}
get_final_scores = function(yr) {
  return(load_nba_schedule(yr) |>
    filter(home_score != 0 & away_score != 0) |>
    transmute(date = game_date,
              win_score = ifelse(home_score > away_score, home_score, away_score),
              lose_score = ifelse(home_score > away_score, away_score, home_score),
              score = paste0(win_score, "-", lose_score)))
}

for (i in 2010:2023) {
  df = get_final_scores(i)
  if (i == 2010) {
    all_final_scores = df
  } else {
    all_final_scores = rbind(all_final_scores, df)
  }
}

last_time_score_happened = function(fscore) {
  return(all_final_scores |>
    filter(score == fscore) |>
    slice_max(date) |>
    head(1) |> pull(date))
}

last_time_score_happened("112-110")
```

### xxx

```{r}
wend_records = end_games |>
  mutate(weekday = wday(date, label = T, abbr = T),
         weekend = ifelse(weekday %in% c("Fri", "Sat", "Sun"), "weekend", "weekday")) |>
  filter(weekend == "weekend") |>
  count(win_team) |>
  rename(team = win_team, weekend_wins = n) |>
  inner_join(end_games |>
  mutate(weekday = wday(date, label = T, abbr = T),
         weekend = ifelse(weekday %in% c("Fri", "Sat", "Sun"), "weekend", "weekday")) |>
  filter(weekend == "weekday") |>
  count(win_team) |>
  rename(team = win_team, weekday_wins = n), by = "team") |>
  inner_join(end_games |>
  mutate(weekday = wday(date, label = T, abbr = T),
         weekend = ifelse(weekday %in% c("Fri", "Sat", "Sun"), "weekend", "weekday")) |>
  filter(weekend == "weekend") |>
  count(lose_team) |>
  rename(team = lose_team, weekend_losses = n), by = "team") |>
  inner_join(end_games |>
  mutate(weekday = wday(date, label = T, abbr = T),
         weekend = ifelse(weekday %in% c("Fri", "Sat", "Sun"), "weekend", "weekday")) |>
  filter(weekend == "weekday") |>
  count(lose_team) |>
  rename(team = lose_team, weekday_losses = n), by = "team") |>
  mutate(weekend_pct = round(weekend_wins / (weekend_wins + weekend_losses), 3),
         weekday_pct = round(weekday_wins / (weekday_wins + weekday_losses), 3))

wend_records |>
  ggplot(aes(weekday_pct, weekend_pct)) +
  geom_point(aes(col = team), size = 4, show.legend = F) +
  geom_line(stat = "smooth", formula = y ~ x, method = "lm", linetype = "dashed", alpha = 0.5) +
  ggrepel::geom_text_repel(aes(label = team), size = 4) +
  annotate("text", x = 0.75, y = 0.25, label = "Better on\nWeekdays", fontface = "italic", alpha = 0.5) +
  annotate("text", x = 0.275, y = 0.75, label = "Better on\nWeekends", fontface = "italic", alpha = 0.5) +
  scale_color_manual(values = team_color_codes) +
  scale_x_continuous(breaks = seq(0, 1, by = 0.1), labels = scales::percent) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1), labels = scales::percent) +
  labs(x = "Weekday Win Percentage", y = "Weekend Win Percentage",
       title = "Win Percentages on Weekdays v. Weekends",
       subtitle = paste0("Correlation: ", round(cor(wend_records$weekday_pct, wend_records$weekend_pct), 3)),
       caption = "Data: NBA.com via {hoopR}")

wend_records |>
  transmute(team, weekday_pct, weekend_pct, diff = weekday_pct - weekend_pct, abs_diff = abs(diff)) |>
  arrange(desc(abs_diff))
```



















































